# Generated by Django 2.0.7 on 2018-07-02 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='featured',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
